print('Hello my name is Sanzhar')
print('Hello my name is Test')
print('Hello my name is Beka')
print('Hello my name is Elzar')
print('Hello my name is Chygyz')
print("Hello my name is Bekbolsyn")
print("Hello my name is Nurlan")
print("Hello my name is Orozbek")